import {
  Business,
  User,
  Employee,
  Compensation,
  WorkSchedule,
  AttendanceRecord,
  OvertimeRecord,
  Holiday,
  IncentiveProgram,
  DeductionType,
  EmployeeDeduction,
  PayrollPeriod,
  AuditLog,
  AppNotification,
  SystemSettings,
} from '../types';
import { calculateRates, calculateScheduleMetrics } from './payrollEngine';

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz_iluvkeyks',
    name: 'iLuvKeyks Coffee & Tea',
    code: 'ILK',
    description: 'Artisanal coffee, specialty teas, and freshly baked pastries.',
    address: 'Unit 102, CV Central Commercial Strip, BGC, Taguig City',
    status: 'active',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'biz_hydrapure',
    name: 'HydraPure Water Refilling Station',
    code: 'HPW',
    description: 'Mineral, purified, and alkaline water refilling with home & commercial delivery.',
    address: 'Blk 4 Lot 12, Commercial Hub, Pasig City',
    status: 'active',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'biz_inkfusion',
    name: 'InkFusion Prints & Design',
    code: 'IFP',
    description: 'Custom corporate merchandise, large format printing, and apparel embroidery.',
    address: 'Ground Floor, Creative Arts Bldg, Makati City',
    status: 'active',
    createdAt: '2026-03-10T08:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_carlos',
    employeeId: 'CVG-ADM-001',
    fullName: 'Carlos Valderama',
    email: 'admin@cvgroup.com',
    mobileNumber: '+63 917 888 1234',
    role: 'super_admin',
    businessId: 'all',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_maria',
    employeeId: 'HPW-MGR-001',
    fullName: 'Maria Elena Santos',
    email: 'maria.santos@hydrapure.com',
    mobileNumber: '+63 918 555 6789',
    role: 'business_admin',
    businessId: 'biz_hydrapure',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_joshua',
    employeeId: 'ILK-EMP-101',
    fullName: 'Joshua De Leon',
    email: 'joshua.deleon@iluvkeyks.com',
    mobileNumber: '+63 920 123 4567',
    role: 'employee',
    businessId: 'biz_iluvkeyks',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_rico',
    employeeId: 'HPW-EMP-204',
    fullName: 'Rico Bautista',
    email: 'rico.bautista@hydrapure.com',
    mobileNumber: '+63 929 444 8899',
    role: 'employee',
    businessId: 'biz_hydrapure',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr_annalyn',
    employeeId: 'IFP-EMP-305',
    fullName: 'Annalyn Ramos',
    email: 'annalyn.ramos@inkfusion.com',
    mobileNumber: '+63 939 777 3322',
    role: 'employee',
    businessId: 'biz_inkfusion',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'usr_carlos',
    employeeId: 'CVG-ADM-001',
    fullName: 'Carlos Valderama',
    mobileNumber: '+63 917 888 1234',
    email: 'admin@cvgroup.com',
    businessId: 'biz_iluvkeyks',
    position: 'Chief Executive Officer',
    employmentStatus: 'regular',
    dateHired: '2024-01-01',
    accountStatus: 'active',
    role: 'super_admin',
  },
  {
    id: 'usr_maria',
    employeeId: 'HPW-MGR-001',
    fullName: 'Maria Elena Santos',
    mobileNumber: '+63 918 555 6789',
    email: 'maria.santos@hydrapure.com',
    businessId: 'biz_hydrapure',
    position: 'Branch Operations Manager',
    employmentStatus: 'regular',
    dateHired: '2025-02-15',
    accountStatus: 'active',
    role: 'business_admin',
    assignedBusinessIds: ['biz_hydrapure'],
  },
  {
    id: 'usr_joshua',
    employeeId: 'ILK-EMP-101',
    fullName: 'Joshua De Leon',
    mobileNumber: '+63 920 123 4567',
    email: 'joshua.deleon@iluvkeyks.com',
    businessId: 'biz_iluvkeyks',
    position: 'Senior Barista & Shift Lead',
    employmentStatus: 'regular',
    dateHired: '2025-05-10',
    accountStatus: 'active',
    role: 'employee',
  },
  {
    id: 'usr_rico',
    employeeId: 'HPW-EMP-204',
    fullName: 'Rico Bautista',
    mobileNumber: '+63 929 444 8899',
    email: 'rico.bautista@hydrapure.com',
    businessId: 'biz_hydrapure',
    position: 'Refilling & Logistics Specialist',
    employmentStatus: 'regular',
    dateHired: '2025-06-01',
    accountStatus: 'active',
    role: 'employee',
  },
  {
    id: 'usr_annalyn',
    employeeId: 'IFP-EMP-305',
    fullName: 'Annalyn Ramos',
    mobileNumber: '+63 939 777 3322',
    email: 'annalyn.ramos@inkfusion.com',
    businessId: 'biz_inkfusion',
    position: 'Graphic Print Technician',
    employmentStatus: 'regular',
    dateHired: '2025-08-20',
    accountStatus: 'active',
    role: 'employee',
  },
];

export const INITIAL_COMPENSATIONS: Compensation[] = [
  {
    id: 'comp_carlos',
    employeeId: 'usr_carlos',
    dailyRate: 1500,
    requiredWorkingHours: 8,
    hourlyRate: 187.5,
    perMinuteRate: 3.125,
    overtimeRateType: 'multiplier',
    overtimeRateOrMultiplier: 1.25,
    holidayDutyRateType: 'multiplier',
    holidayDutyRateOrMultiplier: 2.0,
    effectiveDate: '2026-01-01',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'comp_maria',
    employeeId: 'usr_maria',
    dailyRate: 950,
    requiredWorkingHours: 8,
    hourlyRate: 118.75,
    perMinuteRate: 1.9792,
    overtimeRateType: 'multiplier',
    overtimeRateOrMultiplier: 1.25,
    holidayDutyRateType: 'multiplier',
    holidayDutyRateOrMultiplier: 2.0,
    effectiveDate: '2026-01-01',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'comp_joshua',
    employeeId: 'usr_joshua',
    dailyRate: 610, // ₱610/day
    requiredWorkingHours: 8,
    hourlyRate: 76.25, // ₱76.25/hr
    perMinuteRate: 1.2708, // ₱1.27/min
    overtimeRateType: 'multiplier',
    overtimeRateOrMultiplier: 1.25, // 125% OT
    holidayDutyRateType: 'multiplier',
    holidayDutyRateOrMultiplier: 2.0, // 200% Holiday
    effectiveDate: '2026-01-01',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'comp_rico',
    employeeId: 'usr_rico',
    dailyRate: 580, // ₱580/day
    requiredWorkingHours: 8,
    hourlyRate: 72.5,
    perMinuteRate: 1.2083,
    overtimeRateType: 'fixed',
    overtimeRateOrMultiplier: 95.0, // ₱95.00 fixed OT hourly
    holidayDutyRateType: 'multiplier',
    holidayDutyRateOrMultiplier: 2.0,
    effectiveDate: '2026-01-01',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'comp_annalyn',
    employeeId: 'usr_annalyn',
    dailyRate: 650, // ₱650/day
    requiredWorkingHours: 8,
    hourlyRate: 81.25,
    perMinuteRate: 1.3542,
    overtimeRateType: 'multiplier',
    overtimeRateOrMultiplier: 1.3, // 130% OT
    holidayDutyRateType: 'multiplier',
    holidayDutyRateOrMultiplier: 2.0,
    effectiveDate: '2026-01-01',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_SCHEDULES: WorkSchedule[] = [
  {
    id: 'sched_joshua',
    employeeId: 'usr_joshua',
    requiredDutyDays: [1, 2, 3, 4, 5, 6], // Mon-Sat
    requiredTimeIn: '08:00',
    requiredBreakOut: '12:00',
    requiredBreakIn: '13:00',
    requiredTimeOut: '17:00',
    totalDutyDurationHours: 9,
    requiredBreakDurationHours: 1,
    netRequiredWorkingHours: 8,
    exceedsEightHoursWarning: false,
  },
  {
    id: 'sched_rico',
    employeeId: 'usr_rico',
    requiredDutyDays: [1, 2, 3, 4, 5, 6], // Mon-Sat
    requiredTimeIn: '07:30',
    requiredBreakOut: '11:30',
    requiredBreakIn: '12:30',
    requiredTimeOut: '16:30',
    totalDutyDurationHours: 9,
    requiredBreakDurationHours: 1,
    netRequiredWorkingHours: 8,
    exceedsEightHoursWarning: false,
  },
  {
    id: 'sched_annalyn',
    employeeId: 'usr_annalyn',
    requiredDutyDays: [1, 2, 3, 4, 5], // Mon-Fri
    requiredTimeIn: '08:30',
    requiredBreakOut: '12:00',
    requiredBreakIn: '13:00',
    requiredTimeOut: '17:30',
    totalDutyDurationHours: 9,
    requiredBreakDurationHours: 1,
    netRequiredWorkingHours: 8,
    exceedsEightHoursWarning: false,
  },
];

export const INITIAL_HOLIDAYS: Holiday[] = [
  {
    id: 'hol_1',
    date: '2026-08-21',
    name: 'Ninoy Aquino Day',
    type: 'special_non_working',
    rateMultiplier: 1.3,
    applicableBusinesses: ['all'],
    notes: 'National Special Non-Working Day',
  },
  {
    id: 'hol_2',
    date: '2026-08-31',
    name: 'National Heroes Day',
    type: 'regular',
    rateMultiplier: 2.0,
    applicableBusinesses: ['all'],
    notes: 'Regular National Holiday (Double Pay)',
  },
  {
    id: 'hol_3',
    date: '2026-09-08',
    name: 'Feast of the Nativity of the Blessed Virgin Mary',
    type: 'special_working',
    rateMultiplier: 1.0,
    applicableBusinesses: ['all'],
    notes: 'Special Working Holiday',
  },
  {
    id: 'hol_4',
    date: '2026-11-01',
    name: "All Saints' Day",
    type: 'special_non_working',
    rateMultiplier: 1.3,
    applicableBusinesses: ['all'],
    notes: 'Special Non-Working Holiday (130%)',
  },
  {
    id: 'hol_5',
    date: '2026-11-30',
    name: 'Bonifacio Day',
    type: 'regular',
    rateMultiplier: 2.0,
    applicableBusinesses: ['all'],
    notes: 'Regular Holiday (200%)',
  },
  {
    id: 'hol_6',
    date: '2026-12-25',
    name: 'Christmas Day',
    type: 'regular',
    rateMultiplier: 2.0,
    applicableBusinesses: ['all'],
    notes: 'Regular Holiday (200%)',
  },
];

export const INITIAL_INCENTIVE_PROGRAMS: IncentiveProgram[] = [
  {
    id: 'inc_perfect_att',
    name: 'Perfect Attendance Incentive',
    description: '₱500 cash incentive per payroll cut-off for zero tardiness and zero unscheduled absences.',
    amount: 500,
    type: 'condition_based',
    conditions: {
      requireNoLate: true,
      requireNoAbsence: true,
      disqualifyOnValidAbsence: true, // Company policy: valid/authorized absence still disqualifies
      minDaysPresent: 5,
    },
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'inc_barista_star',
    name: 'Coffee Master & Cleanliness Bonus',
    description: '₱400 monthly store cleanliness and customer satisfaction bonus for iLuvKeyks staff.',
    amount: 400,
    type: 'condition_based',
    conditions: {
      requireNoLate: false,
      requireNoAbsence: false,
      disqualifyOnValidAbsence: false,
      minDaysPresent: 8,
    },
    applicableBusinessId: 'biz_iluvkeyks',
    effectiveDate: '2026-02-01',
    status: 'active',
  },
  {
    id: 'inc_print_quota',
    name: 'Print Production Target Incentive',
    description: '₱600 production bonus for on-time delivery on print orders at InkFusion.',
    amount: 600,
    type: 'automatic',
    conditions: {
      requireNoLate: false,
      requireNoAbsence: false,
      disqualifyOnValidAbsence: false,
    },
    applicableBusinessId: 'biz_inkfusion',
    effectiveDate: '2026-03-01',
    status: 'active',
  },
];

export const INITIAL_DEDUCTION_TYPES: DeductionType[] = [
  {
    id: 'ded_sss',
    name: 'SSS Contribution',
    category: 'statutory',
    calcType: 'fixed',
    defaultValue: 450,
    isRecurring: true,
    description: 'Social Security System semi-monthly contribution',
    status: 'active',
  },
  {
    id: 'ded_philhealth',
    name: 'PhilHealth Premium',
    category: 'statutory',
    calcType: 'fixed',
    defaultValue: 250,
    isRecurring: true,
    description: 'Philippine Health Insurance Corporation premium share',
    status: 'active',
  },
  {
    id: 'ded_pagibig',
    name: 'Pag-IBIG HDMF',
    category: 'statutory',
    calcType: 'fixed',
    defaultValue: 100,
    isRecurring: true,
    description: 'Home Development Mutual Fund mandatory savings',
    status: 'active',
  },
  {
    id: 'ded_uniform',
    name: 'Company Uniform Installment',
    category: 'uniform',
    calcType: 'fixed',
    defaultValue: 200,
    isRecurring: false,
    description: 'Company uniform fee installment (2 cut-offs)',
    status: 'active',
  },
  {
    id: 'ded_cash_advance',
    name: 'Cash Advance (Vale)',
    category: 'advance',
    calcType: 'manual',
    defaultValue: 0,
    isRecurring: false,
    description: 'Salary cash advance deduction',
    status: 'active',
  },
  {
    id: 'ded_co_loan',
    name: 'Company Emergency Loan',
    category: 'loan',
    calcType: 'fixed',
    defaultValue: 500,
    isRecurring: true,
    description: 'Monthly emergency staff loan amortized over 4 cut-offs',
    status: 'active',
  },
];

export const INITIAL_EMPLOYEE_DEDUCTIONS: EmployeeDeduction[] = [
  // Joshua De Leon (iLuvKeyks)
  {
    id: 'ed_joshua_sss',
    employeeId: 'usr_joshua',
    deductionTypeId: 'ded_sss',
    deductionName: 'SSS Contribution',
    category: 'statutory',
    calcType: 'fixed',
    amount: 450,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_joshua_philhealth',
    employeeId: 'usr_joshua',
    deductionTypeId: 'ded_philhealth',
    deductionName: 'PhilHealth Premium',
    category: 'statutory',
    calcType: 'fixed',
    amount: 250,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_joshua_pagibig',
    employeeId: 'usr_joshua',
    deductionTypeId: 'ded_pagibig',
    deductionName: 'Pag-IBIG HDMF',
    category: 'statutory',
    calcType: 'fixed',
    amount: 100,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  // Rico Bautista (HydraPure)
  {
    id: 'ed_rico_sss',
    employeeId: 'usr_rico',
    deductionTypeId: 'ded_sss',
    deductionName: 'SSS Contribution',
    category: 'statutory',
    calcType: 'fixed',
    amount: 450,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_rico_philhealth',
    employeeId: 'usr_rico',
    deductionTypeId: 'ded_philhealth',
    deductionName: 'PhilHealth Premium',
    category: 'statutory',
    calcType: 'fixed',
    amount: 250,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_rico_pagibig',
    employeeId: 'usr_rico',
    deductionTypeId: 'ded_pagibig',
    deductionName: 'Pag-IBIG HDMF',
    category: 'statutory',
    calcType: 'fixed',
    amount: 100,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  // Annalyn Ramos (InkFusion)
  {
    id: 'ed_annalyn_sss',
    employeeId: 'usr_annalyn',
    deductionTypeId: 'ded_sss',
    deductionName: 'SSS Contribution',
    category: 'statutory',
    calcType: 'fixed',
    amount: 450,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_annalyn_philhealth',
    employeeId: 'usr_annalyn',
    deductionTypeId: 'ded_philhealth',
    deductionName: 'PhilHealth Premium',
    category: 'statutory',
    calcType: 'fixed',
    amount: 250,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_annalyn_pagibig',
    employeeId: 'usr_annalyn',
    deductionTypeId: 'ded_pagibig',
    deductionName: 'Pag-IBIG HDMF',
    category: 'statutory',
    calcType: 'fixed',
    amount: 100,
    isRecurring: true,
    effectiveDate: '2026-01-01',
    status: 'active',
  },
  {
    id: 'ed_annalyn_loan',
    employeeId: 'usr_annalyn',
    deductionTypeId: 'ded_co_loan',
    deductionName: 'Company Emergency Loan (Cutoff 2/4)',
    category: 'loan',
    calcType: 'fixed',
    amount: 350,
    isRecurring: true,
    effectiveDate: '2026-08-16',
    endDate: '2026-10-15',
    status: 'active',
    notes: 'Approved medical emergency loan installment',
  },
];

export const INITIAL_PAYROLL_PERIODS: PayrollPeriod[] = [
  {
    id: 'period_2026_08_2',
    cycle: 'semi_monthly',
    name: 'August 16 – 31, 2026',
    startDate: '2026-08-16',
    endDate: '2026-08-31',
    payoutDate: '2026-09-05',
    status: 'paid',
    finalizedAt: '2026-09-03T16:00:00Z',
    finalizedBy: 'Carlos Valderama',
    paidAt: '2026-09-05T10:30:00Z',
    paidBy: 'Carlos Valderama',
  },
  {
    id: 'period_2026_09_1',
    cycle: 'semi_monthly',
    name: 'September 1 – 15, 2026',
    startDate: '2026-09-01',
    endDate: '2026-09-15',
    payoutDate: '2026-09-20',
    status: 'projected',
  },
  {
    id: 'period_2026_09_2',
    cycle: 'semi_monthly',
    name: 'September 16 – 30, 2026',
    startDate: '2026-09-16',
    endDate: '2026-09-30',
    payoutDate: '2026-10-05',
    status: 'projected',
  },
];

// Realistic historical attendance logs for active period Sept 1 to Sept 11, 2026
export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  // Joshua De Leon (iLuvKeyks) - Required 08:00 - 17:00, Break 12:00 - 13:00
  {
    id: 'att_josh_0901',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-01',
    timeIn: '07:54:12',
    breakOut: '12:03:00',
    breakIn: '12:58:30',
    timeOut: '17:02:15',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 55,
    totalWorkHours: 8.1,
    status: 'present',
    holidayDutyPay: 0,
  },
  {
    id: 'att_josh_0902',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-02',
    timeIn: '07:58:40',
    breakOut: '12:00:10',
    breakIn: '13:00:00',
    timeOut: '17:05:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 60,
    totalWorkHours: 8.1,
    status: 'present',
    holidayDutyPay: 0,
  },
  {
    id: 'att_josh_0903',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-03',
    timeIn: '07:50:00',
    breakOut: '12:05:00',
    breakIn: '12:55:00',
    timeOut: '17:01:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 50,
    totalWorkHours: 8.2,
    status: 'present',
    holidayDutyPay: 0,
  },
  {
    id: 'att_josh_0904',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-04',
    timeIn: '07:56:00',
    breakOut: '12:00:00',
    breakIn: '13:02:00',
    timeOut: '17:00:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 62,
    totalWorkHours: 8.0,
    status: 'present',
    holidayDutyPay: 0,
  },
  // Demonstrating STRICT NO-GRACE PERIOD: 08:14 = 14 mins late!
  {
    id: 'att_josh_0905',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-05',
    timeIn: '08:14:22',
    breakOut: '12:00:00',
    breakIn: '12:59:00',
    timeOut: '17:00:00',
    lateMinutes: 14,
    lateOccurrences: 1,
    lateDeductions: 17.79, // 14 mins * ₱1.2708/min
    requiredBreakMinutes: 60,
    actualBreakMinutes: 59,
    totalWorkHours: 7.77,
    status: 'present',
    holidayDutyPay: 0,
    remarks: 'Heavy traffic on C5 road. Clocked in 8:14 AM.',
  },
  {
    id: 'att_josh_0907',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-07',
    timeIn: '07:55:00',
    breakOut: '12:02:00',
    breakIn: '13:00:00',
    timeOut: '17:01:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 58,
    totalWorkHours: 8.1,
    status: 'present',
    holidayDutyPay: 0,
  },
  {
    id: 'att_josh_0908',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-08',
    timeIn: '07:52:00',
    breakOut: '12:00:00',
    breakIn: '13:00:00',
    timeOut: '17:00:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 60,
    totalWorkHours: 8.0,
    status: 'present',
    isHoliday: true,
    holidayName: 'Feast of the Nativity of Mary',
    holidayRateMultiplier: 1.0,
    holidayDutyPay: 0,
  },
  {
    id: 'att_josh_0909',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-09',
    timeIn: '07:58:00',
    breakOut: '12:00:00',
    breakIn: '12:59:00',
    timeOut: '17:03:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 59,
    totalWorkHours: 8.08,
    status: 'present',
    holidayDutyPay: 0,
  },
  {
    id: 'att_josh_0910',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-10',
    timeIn: '07:59:15',
    breakOut: '12:00:00',
    breakIn: '13:00:00',
    timeOut: '17:00:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 60,
    totalWorkHours: 8.0,
    status: 'present',
    holidayDutyPay: 0,
  },
  // Sept 11: Joshua stayed until 18:35 (Required 17:00 => 95 mins OT > 60m min)
  {
    id: 'att_josh_0911',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-11',
    timeIn: '07:55:00',
    breakOut: '12:00:00',
    breakIn: '13:00:00',
    timeOut: '18:35:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 60,
    totalWorkHours: 9.58,
    status: 'present',
    holidayDutyPay: 0,
  },

  // Rico Bautista (HydraPure) - Clean attendance! 0 late, 0 absent
  ...[
    '2026-09-01',
    '2026-09-02',
    '2026-09-03',
    '2026-09-04',
    '2026-09-05',
    '2026-09-07',
    '2026-09-08',
    '2026-09-09',
    '2026-09-10',
    '2026-09-11',
  ].map((d, idx) => ({
    id: `att_rico_${idx + 1}`,
    employeeId: 'usr_rico',
    businessId: 'biz_hydrapure',
    date: d,
    timeIn: '07:25:00',
    breakOut: '11:30:00',
    breakIn: '12:28:00',
    timeOut: '16:30:00',
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 58,
    totalWorkHours: 8.05,
    status: 'present' as const,
    holidayDutyPay: 0,
  })),

  // Annalyn Ramos (InkFusion)
  ...[
    '2026-09-01',
    '2026-09-02',
    '2026-09-03',
    '2026-09-04',
    '2026-09-07',
    '2026-09-08',
    '2026-09-09',
    '2026-09-10',
    '2026-09-11',
  ].map((d, idx) => ({
    id: `att_annalyn_${idx + 1}`,
    employeeId: 'usr_annalyn',
    businessId: 'biz_inkfusion',
    date: d,
    timeIn: '08:26:00',
    breakOut: '12:00:00',
    breakIn: '13:00:00',
    timeOut: d === '2026-09-09' ? '18:45:00' : '17:31:00', // 75 mins OT on 09-09
    lateMinutes: 0,
    lateOccurrences: 0,
    lateDeductions: 0,
    requiredBreakMinutes: 60,
    actualBreakMinutes: 60,
    totalWorkHours: d === '2026-09-09' ? 9.25 : 8.02,
    status: 'present' as const,
    holidayDutyPay: 0,
  })),
];

export const INITIAL_OVERTIME_RECORDS: OvertimeRecord[] = [
  {
    id: 'ot_josh_0911',
    employeeId: 'usr_joshua',
    businessId: 'biz_iluvkeyks',
    date: '2026-09-11',
    requiredTimeOut: '17:00',
    actualTimeOut: '18:35',
    totalExcessMinutes: 95,
    potentialOvertimeMinutes: 95,
    status: 'pending', // Pending Super Admin Approval
    calculatedPay: 150.91, // (95 / 60) * 76.25 * 1.25
    rateApplied: 1.25,
    rateTypeApplied: 'multiplier',
    reviewNotes: 'Assisted with bulk weekend tea batch brewing & store inventory count.',
  },
  {
    id: 'ot_annalyn_0909',
    employeeId: 'usr_annalyn',
    businessId: 'biz_inkfusion',
    date: '2026-09-09',
    requiredTimeOut: '17:30',
    actualTimeOut: '18:45',
    totalExcessMinutes: 75,
    potentialOvertimeMinutes: 75,
    status: 'approved', // Approved by Super Admin!
    calculatedPay: 132.03, // (75 / 60) * 81.25 * 1.3
    rateApplied: 1.3,
    rateTypeApplied: 'multiplier',
    reviewedBy: 'Carlos Valderama',
    reviewedAt: '2026-09-10T09:15:00Z',
    reviewNotes: 'Approved: Urgent corporate banner printing deadline for client expo.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_1',
    userId: 'usr_carlos',
    userName: 'Carlos Valderama',
    action: 'Overtime Approved',
    category: 'overtime',
    previousValue: 'Status: Pending (75 mins)',
    newValue: 'Status: Approved (₱132.03 payable)',
    timestamp: '2026-09-10T09:15:00Z',
    details: 'Approved overtime for Annalyn Ramos (InkFusion Prints) for date 2026-09-09',
  },
  {
    id: 'aud_2',
    userId: 'usr_carlos',
    userName: 'Carlos Valderama',
    action: 'Finalized Payroll Cut-off',
    category: 'payroll',
    previousValue: 'Period August 16–31, 2026: Status For Review',
    newValue: 'Period August 16–31, 2026: Status Finalized & Locked',
    timestamp: '2026-09-03T16:00:00Z',
    details: 'Locked all earnings, rates, and deduction historical snapshots.',
  },
  {
    id: 'aud_3',
    userId: 'usr_carlos',
    userName: 'Carlos Valderama',
    action: 'Paid Payroll Released',
    category: 'payroll',
    previousValue: 'Status: Finalized',
    newValue: 'Status: Paid (Bank Disbursed)',
    timestamp: '2026-09-05T10:30:00Z',
    details: 'All payroll salaries released to employee accounts.',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    targetUserId: 'usr_carlos',
    targetRole: 'super_admin',
    title: 'Overtime Review Required',
    message: 'Joshua De Leon (iLuvKeyks) recorded 95 minutes of overtime on Sept 11, 2026.',
    type: 'warning',
    read: false,
    createdAt: '2026-09-11T18:36:00Z',
    link: 'overtime',
  },
  {
    id: 'notif_2',
    targetUserId: 'usr_annalyn',
    title: 'Overtime Approved',
    message: 'Your overtime request of 75 minutes on Sept 9, 2026 has been approved by Super Admin.',
    type: 'success',
    read: true,
    createdAt: '2026-09-10T09:15:00Z',
    link: 'expected_salary',
  },
  {
    id: 'notif_3',
    targetUserId: 'usr_joshua',
    title: 'Incentive Status Update',
    message: 'Notice: 1 tardiness shift recorded on Sept 5 (14 mins late). Perfect Attendance incentive currently disqualified.',
    type: 'warning',
    read: false,
    createdAt: '2026-09-05T08:15:00Z',
    link: 'incentives',
  },
  {
    id: 'notif_4',
    targetRole: 'super_admin',
    title: 'Payroll Cycle Active',
    message: 'Current payroll cut-off (Sept 1–15, 2026) calculations updated live with attendance.',
    type: 'info',
    read: true,
    createdAt: '2026-09-01T08:00:00Z',
    link: 'payroll',
  },
];

export const INITIAL_SYSTEM_SETTINGS: SystemSettings = {
  minimumOvertimeMinutes: 60, // Default 1 hour minimum
  payrollCycle: 'semi_monthly',
  allowManualAttendanceAdjustments: true,
  requireAuditReasonForAdjustments: true,
  cctvNoticeText: 'Please stand directly within view of the company CCTV camera when performing Time In, Break, or Time Out actions for visual verification.',
};
